/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtikelIndexRouteImport } from './routes/artikel.index'
import { Route as ArtikelSlugRouteImport } from './routes/artikel.$slug'
import { Route as KatalogIndexRouteImport } from './routes/katalog.index'
import { Route as KatalogSlugRouteImport } from './routes/katalog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelIndexRoute = ArtikelIndexRouteImport.update({
  id: '/artikel/',
  path: '/artikel/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelSlugRoute = ArtikelSlugRouteImport.update({
  id: '/artikel/$slug',
  path: '/artikel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogIndexRoute = KatalogIndexRouteImport.update({
  id: '/katalog/',
  path: '/katalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogSlugRoute = KatalogSlugRouteImport.update({
  id: '/katalog/$slug',
  path: '/katalog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/katalog/$slug': typeof KatalogSlugRoute
  '/artikel/': typeof ArtikelIndexRoute
  '/katalog/': typeof KatalogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/katalog/$slug': typeof KatalogSlugRoute
  '/artikel': typeof ArtikelIndexRoute
  '/katalog': typeof KatalogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/katalog/$slug': typeof KatalogSlugRoute
  '/artikel/': typeof ArtikelIndexRoute
  '/katalog/': typeof KatalogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/artikel/$slug' | '/katalog/$slug' | '/artikel/' | '/katalog/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/artikel/$slug' | '/katalog/$slug' | '/artikel' | '/katalog'
  id:
    | '__root__'
    | '/'
    | '/artikel/$slug'
    | '/katalog/$slug'
    | '/artikel/'
    | '/katalog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtikelSlugRoute: typeof ArtikelSlugRoute
  KatalogSlugRoute: typeof KatalogSlugRoute
  ArtikelIndexRoute: typeof ArtikelIndexRoute
  KatalogIndexRoute: typeof KatalogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel/': {
      id: '/artikel/'
      path: '/artikel'
      fullPath: '/artikel/'
      preLoaderRoute: typeof ArtikelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel/$slug': {
      id: '/artikel/$slug'
      path: '/artikel/$slug'
      fullPath: '/artikel/$slug'
      preLoaderRoute: typeof ArtikelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog/': {
      id: '/katalog/'
      path: '/katalog'
      fullPath: '/katalog/'
      preLoaderRoute: typeof KatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog/$slug': {
      id: '/katalog/$slug'
      path: '/katalog/$slug'
      fullPath: '/katalog/$slug'
      preLoaderRoute: typeof KatalogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtikelSlugRoute: ArtikelSlugRoute,
  KatalogSlugRoute: KatalogSlugRoute,
  ArtikelIndexRoute: ArtikelIndexRoute,
  KatalogIndexRoute: KatalogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
